version: '3'
services:
  db-mysql:
    build:
      context: ./db-mysql
      dockerfile: Dockerfile
    container_name: db-mysql
    command: --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: 1171007
      MYSQL_DATABASE: prueba
      MYSQL_USER: victor
    ports:
      - "3306:3306"